### ISSUE TITLE
Style not found

### ISSUE THREAD

**Issue by feliwir** [anitaa1990/Biometric-Auth-Sample#3]
Hey, i'm getting the following error when trying to use your package:
`Output:  error: resource style/Theme.Design.Light.BottomSheetDialog (aka org.mes:style/Theme.Design.Light.BottomSheetDialog) not found.`

How can i fix this?

**Comment by feliwir** [comment]
Seems like my app was missing `com.android.support:design:28.0.0-alpha1`

**Comment by DhruvaSambrani** [comment]
Shouldn't this be made into a dependency of this library? 
I got the same error and solved this the same way. Please open this issue again so that it can be rectified

**Comment by DhruvaSambrani** [comment]
Infact with migration to AndroidX, com.google.android.material:material:1.0.0 should be used
