### ISSUE TITLE
[How to] Canceling fingerprint scanning ?

### ISSUE THREAD

**Issue by mkorat1717** [anitaa1990/Biometric-Auth-Sample#7]
Fingerprint scanner doesn't stop scanning after choose the CANCEL option.
Step to reproduce
1) Open App and clicked on Login button. This will open up the bottom bar with fingerprint scanning option
2) Choose Cancel button.
3) Cancel callback invoked successfully and able to see the prompt too.
4) Fingerprint scanner still working in background. If user choose to put scan finger again, it prompt callback methods.

Looks like CancellationSignal object doesn't work with .authenticate method.

**Comment by mirjalal** [comment]
After searching for other fingerprint examples I found the solution of your problem in [this example](https://github.com/googlesamples/android-FingerprintDialog/blob/master/Application/src/main/java/com/example/android/fingerprintdialog/FingerprintUiHelper.java#L71) by @googlesamples. I think, @anitaa1990 just forgot to create an object instance of `CancellationSignal` class in [this method](https://github.com/anitaa1990/Biometric-Auth-Sample/blob/8659bf87e7e69393b5f28f619e8d3b4ecdeef146/biometric-auth/src/main/java/com/an/biometric/BiometricManager.java#L77) and cancel it [before firing callback method](https://github.com/anitaa1990/Biometric-Auth-Sample/blob/8659bf87e7e69393b5f28f619e8d3b4ecdeef146/biometric-auth/src/main/java/com/an/biometric/BiometricManager.java#L85).

**Comment by hassanmhd** [comment]
@mkorat1717  You can check my pull request #9 which solves this problem.

**Comment by mkorat1717** [comment]
Thank you guys for your contribution ! Looks #9 fixed the issue.
